# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & test

on:
  pull_request:
  push:
    branches: [ main, release/* ]

env:
  ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install jextract
      shell: sh
      run: |
        wget -qO- https://download.java.net/java/early_access/jextract/1/openjdk-21-jextract+1-2_linux-x64_bin.tar.gz | tar xvz
        echo "$PWD/jextract-21/bin" >> $GITHUB_PATH

    - uses: burrunan/gradle-cache-action@a54b6ce2cbbba932e5d142129dddef103e6ad143 #v1.19
      name: Build with Gradle
      with:
        read-only: ${{ github.ref != 'refs/heads/main' && !contains(github.ref, 'release/') }}
        arguments: build

    - uses: burrunan/gradle-cache-action@a54b6ce2cbbba932e5d142129dddef103e6ad143 #v1.19
      name: Publish Maven artifacts
      if: ${{ github.ref == 'refs/heads/main' || contains(github.ref, 'release/') }}
      with:
        arguments: publish

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Results Linux
        path: '**/test-results/**/*.xml'

  publish-test-results:
      name: Publish Test Results
      needs: [linux]
      runs-on: ubuntu-latest
      if: success() || failure()

      steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: test-results

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@62516aa379bff6370c95fd5894d5a27fb6619d9b # v5.2.0
        with:
          report_paths: test-results/**/*.xml
