# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & test

on:
  pull_request:
  push:
    branches: [ main, release/* ]

env:
  ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3

    - uses: sormuras/download-jdk@v1
      with:
        feature: Panama

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ env.JDK_VERSION }}
        distribution: jdkfile
        jdkFile: ${{ env.JDK_FILE }}

    - uses: burrunan/gradle-cache-action@cbdf4342ff988d143aa7a5aeceedffafb8c74bcf #v1.10
      name: Build with Gradle
      with:
        read-only: ${{ github.ref != 'refs/heads/main' && !contains(github.ref, 'release/') }}
        arguments: build

    - uses: burrunan/gradle-cache-action@cbdf4342ff988d143aa7a5aeceedffafb8c74bcf #v1.10
      name: Publish Maven artifacts
      if: ${{ github.ref == 'refs/heads/main' || contains(github.ref, 'release/') }}
      with:
        arguments: publish

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Test Results Linux
        path: '**/test-results/**/*.xml'

  publish-test-results:
      name: Publish Test Results
      needs: [linux]
      runs-on: ubuntu-latest
      if: success() || failure()

      steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: test-results

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@7210fead7f92f6395c37241964df3b0f730f5e4e
        with:
          report_paths: test-results/**/*.xml
